title: Ocean Best Practices System
email: info@oceanbestpractices.org
description: >-
  Providing technological advances and community approaches for all ocean methods 
  to better understand and sustain our oceans.
baseurl: "" # the subpath of your site, e.g. /project-name
url: "https://oceanbestpractices.org" # Updated if a new domain is available, or keep as placeholder

# Social links
#twitter_username: oceanbestpract
#github_username: oceanbestpractices

# Build settings
theme: minima

# Custom CSS
# Minima by default looks for assets/main.scss, but we can also use custom styles
# Alternatively, we can just use the minima defaults and override them.
# However, many Jekyll sites use assets/main.scss for this.
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - index.md
  - repository.md
  - journal.md
  - about.md

# Custom Variables
vision: "To have agreed and broadly adopted methods across ocean research, operations and applications."
footer_text: "Copyright © 2026 UNESCO/IOC Project office for IODE Oostende, Belgium."
